version: "3"

services:
  app:
    image: my-app:latest
    build:
      context: .
      dockerfile: Dockerfile.firefox
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host